sudo: false
language: ruby
rvm:
  - 2.2.6
  - 2.3.3
  - 2.4.1
cache:
  bundler: true
  directories:
    - node_modules

install:
  - bundle install
  - nvm install node
  - node -v
  - npm install
script:
  - npm run lint
  - bundle exec rubocop
  - bundle exec rake test
